//! Shared graph representations, generators, and loading helpers for the
//! ε-serde vs rkyv benchmarks.

use std::{
    fs::File,
    io::{Read, Write},
    path::Path,
};

use anyhow::{Context, Result};
use epserde::prelude::*;
use rand::{Rng, SeedableRng, rngs::SmallRng};
use rkyv::{rancor::Error as RkyvError, util::AlignedVec, vec::ArchivedVec};

/// Minimal read-only graph interface shared by the three representations.
pub trait Graph {
    fn num_nodes(&self) -> usize;
    fn successors(&self, node: usize) -> &[u64];
}

impl Graph for Vec<Vec<u64>> {
    #[inline(always)]
    fn num_nodes(&self) -> usize {
        self.len()
    }
    #[inline(always)]
    fn successors(&self, node: usize) -> &[u64] {
        &self[node]
    }
}

/// ε-serde's ε-copy deserialization type for `Vec<Vec<u64>>`.
impl Graph for Vec<&[u64]> {
    #[inline(always)]
    fn num_nodes(&self) -> usize {
        self.len()
    }
    #[inline(always)]
    fn successors(&self, node: usize) -> &[u64] {
        self[node]
    }
}

/// rkyv's archived type for `Vec<Vec<u64>>` (with default features, archived
/// `u64` is a native `u64`).
impl Graph for ArchivedVec<ArchivedVec<u64>> {
    #[inline(always)]
    fn num_nodes(&self) -> usize {
        self.len()
    }
    #[inline(always)]
    fn successors(&self, node: usize) -> &[u64] {
        self[node].as_slice()
    }
}

/// Directed G(n, p) with p = degree / n, generated by geometric skipping
/// (Batagelj–Brandes); adjacency lists come out sorted and without
/// self-loops.
pub fn erdos_renyi(n: usize, degree: f64, seed: u64) -> Vec<Vec<u64>> {
    let p = (degree / n as f64).min(1.0);
    let log_q = (1.0 - p).ln();
    let mut rng = SmallRng::seed_from_u64(seed);
    let mut graph = Vec::with_capacity(n);
    for u in 0..n {
        let mut succ = Vec::new();
        let mut v: i64 = -1;
        loop {
            let r: f64 = rng.random();
            // Skip length ~ Geometric(p); `ln(r)` with r in [0, 1) is <= 0.
            let skip = (r.max(f64::MIN_POSITIVE).ln() / log_q).floor() as i64;
            v += skip + 1;
            if v >= n as i64 {
                break;
            }
            if v as usize != u {
                succ.push(v as u64);
            }
        }
        graph.push(succ);
    }
    graph
}

/// Random `degree`-regular digraph whose successor lists are the images of
/// the node under `degree` independent random cyclic permutations (Sattolo's
/// algorithm). Following the `i % degree`-th successor at step `i` applies the
/// composition of the permutations every `degree` steps, so the chase does not
/// fall into a short cycle: with degree 1 it visits all nodes, and in general
/// the cycle through node 0 has expected length about `n / 2`. Independent
/// uniform successors would instead trap the chase in a cycle of about
/// `sqrt(n * degree)` states, which fits in cache.
pub fn random_regular(n: usize, degree: usize, seed: u64) -> Vec<Vec<u64>> {
    let mut rng = SmallRng::seed_from_u64(seed);
    let mut graph: Vec<Vec<u64>> = (0..n).map(|_| Vec::with_capacity(degree)).collect();
    let mut perm: Vec<u64> = (0..n as u64).collect();
    for _ in 0..degree {
        for i in (1..n).rev() {
            let j = rng.random_range(0..i);
            perm.swap(i, j);
        }
        for (u, &v) in perm.iter().enumerate() {
            graph[u].push(v);
        }
    }
    graph
}

pub enum Bytes {
    Mem(AlignedVec),
    Mmap(memmap2::Mmap),
}

impl AsRef<[u8]> for Bytes {
    fn as_ref(&self) -> &[u8] {
        match self {
            Bytes::Mem(v) => v.as_slice(),
            Bytes::Mmap(m) => m,
        }
    }
}

pub fn read_rkyv(path: &Path, mmap: bool) -> Result<Bytes> {
    let file = File::open(path)?;
    if mmap {
        // SAFETY: the file is not modified while mapped.
        Ok(Bytes::Mmap(unsafe { memmap2::Mmap::map(&file)? }))
    } else {
        let len = file.metadata()?.len() as usize;
        let mut buf = AlignedVec::<16>::with_capacity(len);
        // SAFETY: `AlignedVec` guarantees `len` bytes of capacity.
        unsafe { buf.set_len(len) };
        std::io::BufReader::new(file).read_exact(buf.as_mut_slice())?;
        Ok(Bytes::Mem(buf))
    }
}

/// Serializes `graph` with both libraries into `dir` and loads the results
/// back, in memory or memory-mapped.
pub struct Fixture {
    pub graph: Vec<Vec<u64>>,
    eps: MemCase<Vec<Vec<u64>>>,
    rkyv_bytes: Bytes,
}

impl Fixture {
    pub fn new(graph: Vec<Vec<u64>>, dir: &Path, mmap: bool) -> Result<Self> {
        let eps_path = dir.join("graph.epserde");
        // SAFETY: serialization of a plain `Vec<Vec<u64>>`.
        unsafe { graph.store(&eps_path)? };
        let rkyv_path = dir.join("graph.rkyv");
        let bytes = rkyv::to_bytes::<RkyvError>(&graph).context("rkyv serialization")?;
        File::create(&rkyv_path)?.write_all(&bytes)?;
        drop(bytes);
        // SAFETY: the file was just written by ε-serde from a `Vec<Vec<u64>>`.
        let eps = unsafe {
            if mmap {
                <Vec<Vec<u64>>>::mmap(&eps_path, Flags::empty())?
            } else {
                <Vec<Vec<u64>>>::load_mem(&eps_path)?
            }
        };
        let rkyv_bytes = read_rkyv(&rkyv_path, mmap)?;
        let this = Self {
            graph,
            eps,
            rkyv_bytes,
        };
        // Sanity check: identical graphs.
        let n = this.graph.len();
        assert_eq!(this.eps().num_nodes(), n);
        assert_eq!(this.rkyv().num_nodes(), n);
        for u in 0..n {
            assert_eq!(this.eps().successors(u), this.graph.successors(u));
            assert_eq!(this.rkyv().successors(u), this.graph.successors(u));
        }
        Ok(this)
    }

    pub fn file_sizes(&self, dir: &Path) -> Result<(u64, u64)> {
        Ok((
            std::fs::metadata(dir.join("graph.epserde"))?.len(),
            std::fs::metadata(dir.join("graph.rkyv"))?.len(),
        ))
    }

    /// ε-serde's ε-copy deserialized graph.
    pub fn eps(&self) -> &Vec<&[u64]> {
        self.eps.uncase()
    }

    /// rkyv's archived graph (accessed without validation).
    pub fn rkyv(&self) -> &ArchivedVec<ArchivedVec<u64>> {
        // SAFETY: the bytes were written by rkyv from a `Vec<Vec<u64>>`.
        unsafe { rkyv::access_unchecked(self.rkyv_bytes.as_ref()) }
    }
}

/// Control representation: ε-serde's data buffer with a header vector of
/// rkyv-style relative pointers (offset from the header's own address, plus
/// length), resolved with an add on every access. It isolates the cost of
/// relative resolution from differences in memory layout between the two
/// libraries.
pub struct RelGraph<'a> {
    headers: Vec<(isize, usize)>,
    _data: &'a Vec<&'a [u64]>,
}

impl<'a> RelGraph<'a> {
    pub fn new(eps: &'a Vec<&'a [u64]>) -> Self {
        let mut headers: Vec<(isize, usize)> = Vec::with_capacity(eps.len());
        let base = headers.as_ptr() as *const u8;
        for (i, s) in eps.iter().enumerate() {
            let header_addr = base.wrapping_add(i * std::mem::size_of::<(isize, usize)>());
            headers.push((
                (s.as_ptr() as *const u8).addr() as isize - header_addr.addr() as isize,
                s.len(),
            ));
        }
        Self {
            headers,
            _data: eps,
        }
    }
}

impl Graph for RelGraph<'_> {
    #[inline(always)]
    fn num_nodes(&self) -> usize {
        self.headers.len()
    }
    #[inline(always)]
    fn successors(&self, node: usize) -> &[u64] {
        let header = &self.headers[node];
        let ptr =
            (header as *const (isize, usize) as *const u8).wrapping_offset(header.0) as *const u64;
        // SAFETY: the offset was computed from a live slice of `_data`.
        unsafe { std::slice::from_raw_parts(ptr, header.1) }
    }
}

/// Control representation replicating rkyv's layout in a single allocation:
/// all list data concatenated, and a (relative offset, length) header per
/// node, with headers placed either after the data (as rkyv does) or before.
pub struct JoinedGraph {
    buf: Vec<u64>,
    headers_start: usize,
    n: usize,
}

impl JoinedGraph {
    pub fn new(graph: &[Vec<u64>], headers_first: bool) -> Self {
        let n = graph.len();
        let data_len: usize = graph.iter().map(Vec::len).sum();
        let mut buf = vec![0u64; data_len + 2 * n];
        let (headers_start, data_start) = if headers_first {
            (0, 2 * n)
        } else {
            (data_len, 0)
        };
        let mut pos = data_start;
        for (i, list) in graph.iter().enumerate() {
            buf[pos..pos + list.len()].copy_from_slice(list);
            let header = headers_start + 2 * i;
            buf[header] = ((pos as isize - header as isize) * 8) as u64;
            buf[header + 1] = list.len() as u64;
            pos += list.len();
        }
        Self {
            buf,
            headers_start,
            n,
        }
    }
}

impl Graph for JoinedGraph {
    #[inline(always)]
    fn num_nodes(&self) -> usize {
        self.n
    }
    #[inline(always)]
    fn successors(&self, node: usize) -> &[u64] {
        let header = &self.buf[self.headers_start + 2 * node..][..2];
        let ptr = (header.as_ptr() as *const u8).wrapping_offset(header[0] as isize) as *const u64;
        // SAFETY: the offset was computed to point inside `buf`.
        unsafe { std::slice::from_raw_parts(ptr, header[1] as usize) }
    }
}
