/*
 * SPDX-FileCopyrightText: 2026 Sebastiano Vigna
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 */

use epserde::TypeInfo;

// full_copy(...) only affects the deserialization type generated by
// derive(Epserde); derive(TypeInfo) must reject it instead of silently
// ignoring it.
#[derive(TypeInfo)]
#[epserde(full_copy(T))]
struct Data<T> {
    a: T,
}

fn main() {}
